name: Deploy VitePress to GitHub Pages and Windows IIS

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build with VitePress
        run: npm run docs:build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

      - name: Prepare IIS Deployment Artifact
        run: |
          mkdir -p dist-iis
          cp -r .vitepress/dist/* dist-iis/
          tar -czf dist-iis.tar.gz dist-iis/

      - name: Upload IIS Artifact
        uses: actions/upload-artifact@v4  # 关键修改：升级到v4版本
        with:
          name: dist-iis
          path: dist-iis.tar.gz

  deploy-to-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-to-iis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download IIS Artifact
        uses: actions/download-artifact@v4  # 关键修改：升级到v4版本
        with:
          name: dist-iis

      - name: Deploy via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist-iis.tar.gz"
          target: "C:\\web\\dist-iis.tar.gz"

      - name: Configure IIS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 创建目标目录
            mkdir C:\web\vitepress-app -Force
            # 解压文件
            tar -xzf C:\web\dist-iis.tar.gz -C C:\web\vitepress-app --strip-components=1
            del C:\web\dist-iis.tar.gz
            # 配置 IIS
            Import-Module WebAdministration
            if (!(Test-Path IIS:\Sites\VitePressSite)) {
              New-WebSite -Name "VitePressSite" -Port 80 -PhysicalPath "C:\web\vitepress-app" -ApplicationPool "DefaultAppPool"
              Add-WebConfiguration -Filter "/system.webServer/defaultDocument/files" -Value @{value='index.html'}
            }
            iisreset /restart