name: Deploy VitePress to IIS (Password Auth)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run docs:build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: .vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Compress files
        run: tar -czf dist.tar.gz -C dist .
      - name: Deploy via SSH (Password)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist.tar.gz"
          target: "C:\\web\\dist.tar.gz"
      - name: Extract and Configure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir C:\web\vitepress -Force
            tar -xzf C:\web\dist.tar.gz -C C:\web\vitepress
            del C:\web\dist.tar.gz
            iisreset /restart