name: Deploy VitePress to GitHub Pages and IIS (Password Auth)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          npm ci
          npm run docs:build
          
          # 调试：显示构建结果
          echo "Build output:"
          ls -la .vitepress/dist

      - name: Create IIS Package
        run: |
          # 确保目录存在
          if [ ! -d ".vitepress/dist" ]; then
            echo "❌ Error: .vitepress/dist not found!"
            ls -la .vitepress
            exit 1
          fi
          
          # 创建压缩包
          tar -czf dist-iis.tar.gz -C .vitepress/dist .
          
          # 验证
          echo "Package contents:"
          tar -tf dist-iis.tar.gz | wc -l

      - uses: actions/upload-artifact@v4
        with:
          name: dist-iis
          path: dist-iis.tar.gz

  deploy-to-iis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-iis

      - name: Debug Package
        run: |
          echo "Downloaded package:"
          ls -la
          echo "Package contents:"
          tar -tf dist-iis.tar.gz | head -n 5

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist-iis.tar.gz"
          target: "C:\\Temp\\"

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # 调试：显示服务器目录
            echo "Server contents before:"
            ls -la C:\web\vitepress-app || echo "Directory not exists"
            
            # 解压到目标目录
            mkdir C:\web\vitepress-app -Force
            tar -xzf C:\Temp\dist-iis.tar.gz -C C:\web\vitepress-app
            
            # 验证
            echo "Server contents after:"
            ls -la C:\web\vitepress-app
            if (!(Test-Path C:\web\vitepress-app\index.html)) {
              echo "❌ Error: index.html not found!"
              exit 1
            }