name: Deploy VitePress to GitHub Pages and IIS (Password Auth)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build with VitePress
        run: npm run docs:build

      # 上传到 GitHub Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

      # 准备 IIS 部署包
      - name: Create IIS Package
        run: |
          # 确保目录存在
          if [ ! -d ".vitepress/dist" ]; then
            echo "❌ Error: .vitepress/dist not found!"
            ls -la .vitepress
            exit 1
          fi
          
          # 创建压缩包
          tar -czf dist-iis.tar.gz -C .vitepress/dist .
          
          # 验证
          echo "Package contents:"
          tar -tf dist-iis.tar.gz | wc -l

      - name: Upload IIS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-iis
          path: dist-iis.tar.gz

  # GitHub Pages 部署
  deploy-to-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Windows IIS 部署（密码认证版）
  deploy-to-iis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-iis

      - name: Deploy via SCP (Password)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist-iis.tar.gz"
          target: "C:\\web\\dist-iis.tar.gz"
          strip_components: 1

      - name: Configure IIS (Password)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            
            # 解压文件
            tar -xzf C:\web\dist-iis.tar.gz -C C:\web\vitepress-app
            
#            # 清理临时文件
#            del C:\web\dist-iis.tar.gz
#
#            # 配置 IIS
#            Import-Module WebAdministration
#            if (!(Test-Path IIS:\Sites\VitePressSite)) {
#              New-WebSite -Name "VitePressSite" -Port 80 -PhysicalPath "C:\web\vitepress-app" -ApplicationPool "DefaultAppPool"
#              Add-WebConfiguration -Filter "/system.webServer/defaultDocument/files" -Value @{value='index.html'}
#            }
#
#            # 设置权限
#            icacls "C:\web\vitepress-app" /grant "IIS_IUSRS:(OI)(CI)R"
#
#            # 重启 IIS
#            iisreset /restart